### ISSUE TITLE
Add checklist for certification application form

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#1379]
The checklist should be managed in an admin ui which is editable by certifcation managers. They will be able to add / remove / edit entries like:

- [ ] have you contributed to the QGIS core application
- [ ] Have you contributed to translations for your language
- [ ] Have you contributed to documentation
- [ ] Do you participate in your national QGIS user group
- [ ] etc...

The admin should not be able to change entries that have already been used, but can archive old ones and replace with new. The admin should be able to set the order in which the checklist is presented.

**Comment by timlinux** [comment]
In the changelog we manage the certification managers among other group permissions

https://changelog.qgis.org/en/project/qgis/update/

![image](https://user-images.githubusercontent.com/178003/148528071-09af768d-06f4-445a-bc8e-32a0fc89d887.png)

This group of managers should see the new menu here:

![image](https://user-images.githubusercontent.com/178003/148528347-b977d606-54b7-49c0-99b3-41094e49f68f.png)


The menu should be hiddent for non managers /non superuser

Change the menu entry to 'Certification Management'

Keep the current options and add more options that the managers should be able to configure:

![image](https://user-images.githubusercontent.com/178003/148529076-4e0e304c-d111-44d2-aea3-497f058c6148.png)


In conjunction with the above, when an application is created for a new org, the reviewer then should see a checklist of the active items in their defined order shown on the certification application request page:

In the pending view: /qgis/pending-certifyingorganisation/list/

![image](https://user-images.githubusercontent.com/178003/148529376-5dbd60ae-3b52-4c09-98ce-73503db85400.png)


Admin user then can fill in a form for the review which lists all the questions

![image](https://user-images.githubusercontent.com/178003/148529879-e4094bd5-aa62-45a2-ae13-f9a2364fb919.png)

The checkbox should rather be a Yes/no/not defined widgets so we can differenciate between null and no and yes.

**Comment by timlinux** [comment]
CC @geomenke

**Comment by timlinux** [comment]
There should also be a read only review view that the aplying organisation can see to see what their review status is. Hans and Kurt to indicate whether the notes should be shown to them.

**Comment by timlinux** [comment]
In addition to above, can we make it that the submitting org also can optionally fill in some basic details for each checklist item:

![imagem](https://user-images.githubusercontent.com/178003/151529079-4a00a0bf-5a6f-435c-9f45-ac2d54fc06ce.png)


In the question admin, there could be a flag to indicate whether the user should see a text box to add detail or not (some checklist items may be more internal and not needing input from the applicant).

**Comment by timlinux** [comment]
![imagem](https://user-images.githubusercontent.com/178003/151529509-32c70702-2f73-4903-b0aa-a468cc9fee77.png)
